### ISSUE TITLE
Share ansible code from last year

### ISSUE THREAD

**Issue by juztas** [cmscaltech/sdn-testbed-puppet#3]
@fno2010 can you share these ansible scripts?

**Comment by fno2010** [comment]
@juztas the ansible scripts are not from me. I remember there was a cmscaltech/sc17 private repo last year. And Vinicius and you contributed to it. But I cannot find it now. I thought you should have the access to it.

**Comment by juztas** [comment]
I dont see anything special there, just few configs. There was in any case a lot manual work. I shared with @fixy and @fno2010 that repo: https://github.com/cmscaltech/sc17

Closing this as it is found. Lets start puppet and we will be good to go.
